#goal definition

#definition of possible Values as Types
uint8 drive = 0
uint8 detect_shelf_layers = 1
uint8 scan_floor_board = 2
uint8 scan_floor_contents = 3
uint8 scan_shelf = 4

uint8 type

#ID of Shelf to drive to or scan
string shelfid

#ID of Floor to scan boarding or content
string floorid

#Pose to drive
geometry_msgs/PoseStamped pose

---
#result definition
float64 result
---
